spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost/myblog?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
#    username: root
#    password: 123456
#    url: jdbc:mysql://1.15.89.54:3306/vtodo_v1?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://127.0.0.1/vtodo_v1?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: mysql5.7VEN

  jpa:
    hibernate:
      ddl-auto: none #实体类确定了，布置到生产环境后，改成none
    show-sql: true #输出sql语句

logging:
  level:
    root: warn #高于此级别的日志才会打印
    com.ven.myblog: info
  file:
    name: log/blog-pro.log
server:
  port: 80
